// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { Stimulus } from '../libs/stimulus'


import ChatController from './chat_controller'
Stimulus.register('chat', ChatController)

import HelloController from './hello_controller'
Stimulus.register('hello', HelloController)

import MessageFormController from './message_form_controller'
Stimulus.register('message-form', MessageFormController)